FORMAT: 1A
HOST: http://localhost:3001/api/v1

# Book Store
This document is mapped all the services of the POC - Book Store. In its version 1.0

AlfaeBeto Soluções

```http
Authorization: bearer 5262d64b892e8d4341000001
```
:[](book.apib)

:[](order.apib)

:[](user.apib)


